version: 1
builder:
  configs:
    - documentation_targets:
        - SwiftDataFrame
        - SwiftStats
        - SwiftPreprocessing
        - SwiftML
        - SwiftCluster
        - SwiftNLP
        - SwiftOptimize
        - SwiftForecast
        - SwiftLLM
        - SwiftExplain
        - SwiftVisualization
        - SwiftVision
        - SwiftDatabase
        - SwiftAgent

